# Composite action to build this project in another workflow.

name: Build Completionist

runs:
  using: composite
  steps:

    - name: Install PHP dependencies
      run: composer install --optimize-autoloader --working-dir="${{ github.action_path }}"
      shell: bash

    - name: Install Node packages
      run: (cd ${{ github.action_path }} && npm install)
      shell: bash

    - name: Build scripts and styles
      run: (cd ${{ github.action_path }} && npm run build)
      shell: bash

    - name: Remove bundle excludes
      run: for PATTERN in $(cat "${{ github.action_path }}/exclude.lst") ; do rm -rf "${{ github.action_path }}/../"${PATTERN} ; done
      shell: bash
