# Composite action to build this project in another workflow.

name: Build Completionist

runs:
  using: composite
  steps:

    - run: composer install --optimize-autoloader --working-dir="${{ github.action_path }}"
      shell: bash

    # Confirm Downloaded Code.
    - run: ls -la "${{ github.action_path }}"
      shell: bash
