# Composite action to build this project in another workflow.

name: Build Completionist

runs:
  using: composite
  steps:

    # Install dependencies.
    - run: composer install --optimize-autoloader --working-dir="${{ github.action_path }}"
      shell: bash

    # Remove excludes.
    - run: xargs rm -rf < "${{ github.action_path }}"/exclude.lst
      shell: bash

    # Review code.
    - run: ls -la "${{ github.action_path }}"
      shell: bash
