# Composite action to build this project in another workflow.

name: Build Completionist

runs:
  using: composite
  steps:

    # - run: composer install --optimize-autoloader
    #   shell: bash

    # Confirm Downloaded Code.
    - run: pwd
      shell: bash

    - run: ls -la
      shell: bash

    - run: echo "${{ github.action_path }}"
      shell: bash
