# Composite action to build this project in another workflow.

name: Build Completionist
steps:

  - name: Install Dependencies
    run: composer install --optimize-autoloader

  # Confirm Downloaded Code.
  - name: Print Working Dir
    run: pwd
  - name: List Working Dir Contents
    run: ls -la
