# Experimental workflow to test GitHub Actions.

name: Build Completionist

on:
  workflow_dispatch:

jobs:

  build:

    name: Build
    runs-on: ubuntu-18.04

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: composer install --optimize-autoloader

      # Confirm Downloaded Code.
      - name: Print Working Dir
        run: pwd
      - name: List Working Dir Contents
        run: ls -la
